version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: catalogo_livros_db
    environment:
      POSTGRES_DB: catalogo_livros
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: